[book]
authors = ["idlesong"]
language = "en"
multilingual = false
src = "src"
title = "gtk-rs guide by examples"
[output.html.fold]
enable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
